name: Node.js Package

on:
  push:
    branches:
      - common-portel-test

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/ 
          scope: '@Mhdnoor06'
      
      - name: Install dependencies
        run: npm install
      
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGES_TOKEN}}
